export const ARTIST_WORKING_LOCATION_TYPE = {
  HOME: "HOME",
  STUDIO: "STUDIO",
};

export const REGISTER_ARTIST_MAX_MEDIA_FILES = 5;

export const USER_ROLE = {
  ADMIN: "ADMIN",
  MEMBER: "MEMBER",
  ARTIST: "ARTIST",
};

export const ARTIST_APPLICATION_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

export const ARTIST_APPLICATION_STATUS_DISPLAY = {
  PENDING: "Chờ duyệt",
  APPROVED: "Đã duyệt",
  REJECTED: "Từ chối",
};

export const ARTIST_WORKING_LOCATION_TYPE_DISPLAY = {
  HOME: "Tại nhà",
  STUDIO: "Studio",
};

export const WEEKDAY = {
  MONDAY: "MONDAY",
  TUESTDAY: "TUESTDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
};

export const REACTION_REFERENCE_TYPE = {
  POST: "POST",
};

export const REACTION_TYPE = {
  LOVE: "LOVE",
};

export const BOOKING_ADDRESS_TYPE = {
  CLIENT_ADDRESS: "CLIENT_ADDRESS",
  ARTIST_ADDRESS: "ARTIST_ADDRESS",
};

export const BOOKING_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};
