export const ARTIST_WORKING_LOCATION_TYPE = {
  HOME: "HOME",
  STUDIO: "STUDIO",
};

export const REGISTER_ARTIST_MAX_MEDIA_FILES = 5;

export const USER_ROLE = {
  ADMIN: "ADMIN",
  MEMBER: "MEMBER",
  ARTIST: "ARTIST",
};

export const ARTIST_APPLICATION_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

export const ARTIST_APPLICATION_STATUS_DISPLAY = {
  PENDING: "Chờ duyệt",
  APPROVED: "Đã duyệt",
  REJECTED: "Từ chối",
};

export const ARTIST_WORKING_LOCATION_TYPE_DISPLAY = {
  HOME: "Tại nhà",
  STUDIO: "Studio",
};
